# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kab/Desktop/workspace/Zedboard_GPIO_LED/Zedboard_GPIO_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_axi_gpio_0_0/design_gpio_led_axi_gpio_0_0.xci
# IP: The module: 'design_gpio_led_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kab/Desktop/workspace/Zedboard_GPIO_LED/Zedboard_GPIO_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_axi_gpio_0_0/design_gpio_led_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_led_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/kab/Desktop/workspace/Zedboard_GPIO_LED/Zedboard_GPIO_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_axi_gpio_0_0/design_gpio_led_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_led_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/kab/Desktop/workspace/Zedboard_GPIO_LED/Zedboard_GPIO_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_axi_gpio_0_0/design_gpio_led_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_led_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/kab/Desktop/workspace/Zedboard_GPIO_LED/Zedboard_GPIO_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_axi_gpio_0_0/design_gpio_led_axi_gpio_0_0.xci
# IP: The module: 'design_gpio_led_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kab/Desktop/workspace/Zedboard_GPIO_LED/Zedboard_GPIO_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_axi_gpio_0_0/design_gpio_led_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_led_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/kab/Desktop/workspace/Zedboard_GPIO_LED/Zedboard_GPIO_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_axi_gpio_0_0/design_gpio_led_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_led_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/kab/Desktop/workspace/Zedboard_GPIO_LED/Zedboard_GPIO_LED.srcs/sources_1/bd/design_gpio_led/ip/design_gpio_led_axi_gpio_0_0/design_gpio_led_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gpio_led_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
